---
- name: Playbook to configure AAP
  hosts: localhost
  gather_facts: false
 
  pre_tasks:
    - name: Include specific project variables
      ansible.builtin.include_vars:
        dir: group_vars

  tasks:
    !
    !
    - name: Import role-aap-object-credential
      ansible.builtin.include_role:
        name: role-aap-object-credential

      vars:
        build: true
        description: "{{ common_description }}"
        organization: "{{ organization_name }}"
        in_list: "{{ item }}"

      loop:
        - "{{ cisco_creds }}"
        - "{{ git_credential }}"
        - "{{ redhat_quay_io_credential }}"
    !
    !
