---
- name: Playbook to configure AAP
  hosts: localhost
  gather_facts: false
 
  pre_tasks:
    - name: Include specific project variables
      ansible.builtin.include_vars:
        dir: group_vars

  tasks:
    !
    !
    - name: Import role-aap-object-credential
      ansible.builtin.include_role:
        name: role-aap-object-credential
      vars:
        build: true
        name: "{{ item.value.credential_name }}"
        organization: "{{ organization_name }}"
        credential_type: "{{ item.value.credential_type }}"
        description: "{{ common_description }}"
        username: "{{ item.value.username }}"
        password: "{{ item.value.password }}"
        # host: "{{ host }}" # If defining Container Registry creds
      loop: "{{ lookup('dict', staging_credentials) }}" 
    !
    !
