---
# Build credential
- name: "Build Container Registry credential - {{ name }}"
  ansible.controller.credential:
    name: "{{ name }}"
    organization: "{{ organization }}"
    state: present
    credential_type: "{{ credential_type }}"
    description: "{{ description }}"
    inputs:
      username: "{{ username }}"
      password: "{{ password }}"
      host: "{{ host }}"
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: false
  when: credential_type == 'Container Registry'
  ignore_errors: true

- name: "Build credential - {{ name }}"
  ansible.controller.credential:
    name: "{{ name }}"
    organization: "{{ organization }}"
    state: present
    credential_type: "{{ credential_type }}"
    description: "{{ description }}"
    inputs:
      username: "{{ username }}"
      password: "{{ password }}"
      # host: "{{ in_list[4] }}"
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: false
  when: credential_type != 'Container Registry'
  ignore_errors: true
