---
# Build credential
- name: "Build Container Registry credential - {{ in_list[0] }}"
  ansible.controller.credential:
    name: "{{ in_list[0] }}"
    organization: "{{ organization }}"
    state: present
    credential_type: "{{ in_list[1] }}"
    description: "{{ description }}"
    inputs:
      username: "{{ in_list[2] }}"
      password: "{{ in_list[3] }}"
      host: "{{ in_list[4] }}"
    validate_certs: false
  when: in_list[1] == 'Container Registry'
  ignore_errors: true

- name: "Build credential - {{ in_list[0] }}"
  ansible.controller.credential:
    name: "{{ in_list[0] }}"
    organization: "{{ organization }}"
    state: present
    credential_type: "{{ in_list[1] }}"
    description: "{{ description }}"
    inputs:
      username: "{{ in_list[2] }}"
      password: "{{ in_list[3] }}"
      # host: "{{ in_list[4] }}"
    validate_certs: false
  when: in_list[1] != 'Container Registry'
  ignore_errors: true
