---
# Build credential
- name: "Build {{ in_list[0] }} credential"
  ansible.controller.credential:
    name: "{{ in_list[0] }}"
    organization: "{{ organization_name }}"
    state: present
    credential_type: "{{ in_list[1] }}"
    description: "{{ common_description }}"
    inputs:
      username: "{{ in_list[2] }}"
      password: "{{ in_list[3] }}"
      # host: "{{ in_list[4] }}"
    validate_certs: false
  when: in_list[1] != 'Container Registry'
    
- name: "Build {{ in_list[0] }} credential"
  ansible.controller.credential:
    name: "{{ in_list[0] }}"
    organization: "{{ organization_name }}"
    state: present
    credential_type: "{{ in_list[1] }}"
    description: "{{ common_description }}"
    inputs:
      username: "{{ in_list[2] }}"
      password: "{{ in_list[3] }}"
      host: "{{ in_list[4] }}"
    validate_certs: false
  when: in_list[1] == 'Container Registry'
